server:
  port: 8888

spring:
  application:
    name: config-service

  profiles:
    active: native

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
      server:
        git:
          uri: https://github.com/tear94fall/modu_messenger_config

management:
  endpoints:
    web:
      exposure:
        include: health, beans, refresh, busrefresh