server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/modu_chat?serverTimezone=Asia/Seoul
    username: root
    password: root1234

  redis:
    host: localhost
    port: 6379

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug

security:
  jwt:
    token:
      secret-key: modu_secret_key
      expire-length: 3600000

project:
  properties:
    firebas-sdk-path: "firebase/modu_chat_firebase_service_key.json"
    firebase-create-scoped: "https://www.googleapis.com/auth/firebase.messaging"
    firebase-topic: "modu_chat_notification"