server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/modu_chat?serverTimezone=Asia/Seoul
    username: root
    password: root1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        default_batch_fetch_size: 10
        open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug

security:
  jwt:
    token:
      secret-key: modu_secret_key
      expire-length: 3600000