server:
  port: 9900

spring:
  application:
    name: auth-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/modu_chat?serverTimezone=Asia/Seoul
    username: root
    password: root1234

  redis:
    host: localhost
    port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411

logging:
  level:
    org.hibernate.SQL: debug

security:
  jwt:
    token:
      access-expired: 3600000
      refresh-expired: 604800000
      secret-key: 98FB6A50D8BE83F0521F6EDA48903D718DE1C41BF09D4D3671A5E3A6E4E0910A
      expire-length: 3600000

eureka:
  instance:
    instance-id: chat-service

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka