server:
  port: 8000

eureka:
  instance:
    instance-id: gateway-service

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  jwt:
    token:
      access-expired: 3600000
      refresh-expired: 604800000
      secret-key: 98FB6A50D8BE83F0521F6EDA48903D718DE1C41BF09D4D3671A5E3A6E4E0910A

spring:
  application:
    name: gateway-service

  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/login
            - Method=POST
          filters:
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/auth/reissue
            - Method=POST
          filters:
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/auth/logout
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/member/signup
            - Method=POST
          filters:
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/member/common/**
            - Method=POST
          filters:
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/chat-service/(?<segment>.*), /$\{segment}
        - id: ws-service
          uri: lb:ws://WS-SERVICE
          predicates:
            - Path=/ws-service/modu-chat/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/ws-service/(?<segment>.*), /$\{segment}
        - id: storage-service
          uri: lb://STORAGE-SERVICE
          predicates:
            - Path=/storage-service/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/storage-service/(?<segment>.*), /$\{segment}
        - id: profile-service
          uri: lb://PROFILE-SERVICE
          predicates:
            - Path=/profile-service/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/profile-service/(?<segment>.*), /$\{segment}