server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local

  application:
    name: member-service

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:tcp://localhost/~/modu-chat
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411

  data:
    redis:
      host: localhost
      port: 6379

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

  circuit-breaker:
    enabled: true

resilience4j:
  retry:
    configs:
      default:
        max-attempts: 5
        waitDuration: 500
    instances:
      customRetry:
        base-config: default
  circuit-breaker:
    configs:
      default:
        waitDurationInOpenState: 30s
        slowCallRateThreshold: 80
        slowCallDurationThreshold: 5s
        registerHealthIndicator: true
    instances:
      default:
        baseConfig: default
  time-limiter:
    configs:
      default:
        timeoutDuration: 5s
        cancelRunningFuture: true

logging:
  level:
    org.hibernate.SQL: debug

management:
  server:
    port: 8082
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    instance-id: member-service

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka