server:
  port: 8080

spring:
  application:
    name: member-service

  profiles:
    default: local
    include: oauth

  config:
    use-legacy-processing: true
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/modu_chat?serverTimezone=Asia/Seoul
    #    url: jdbc:mysql://database:3306/modu-chat
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411

logging:
  level:
    org.hibernate.SQL: debug

eureka:
  instance:
    instance-id: member-service

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka