server:
  port: 8080

spring:
  application:
    name: member-service

  profiles:
    default: local
    include: oauth

  config:
    use-legacy-processing: true
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/modu-chat?serverTimezone=Asia/Seoul
    #    url: jdbc:mysql://database:3306/modu-chat
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

  circuit-breaker:
    enabled: true

resilience4j:
  retry:
    configs:
      default:
        max-attempts: 5
        waitDuration: 500
    instances:
      customRetry:
        base-config: default
  circuit-breaker:
    configs:
      default:
        waitDurationInOpenState: 30s
        slowCallRateThreshold: 80
        slowCallDurationThreshold: 5s
        registerHealthIndicator: true
    instances:
      default:
        baseConfig: default
  time-limiter:
    configs:
      default:
        timeoutDuration: 5s
        cancelRunningFuture: true

logging:
  level:
    org.hibernate.SQL: debug

eureka:
  instance:
    instance-id: member-service

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka