server:
  port: 8090

spring:
  application:
    name: ws-service

  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411

  kafka:
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: localhost:29092
      group-id: chat-broadcast-${random.uuid}
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  instance:
    instance-id: ws-service

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka