server:
  port: 8090

spring:
  application:
    name: ws-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411

eureka:
  instance:
    instance-id: ws-service

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

rabbitmq:
  queue:
    name: modu-chat.queue
  exchange:
    name: modu-chat.exchange
  routing:
    key: modu-chat.key