server:
  port: 8090

spring:
  application:
    name: ws-service

eureka:
  instance:
    instance-id: ws-service

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka