server:
  port: 9999

spring:
  application:
    name: storage-service

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /data

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411

  kafka:
    producer:
      bootstrap-servers: localhost:29092
    consumer:
      bootstrap-servers: localhost:29092
      group-id: storage-service-group

minio:
  endpoint: http://localhost:9000
  accessKey: minio
  secretKey: miniopass
  bucketImageName: file-storage

eureka:
  instance:
    instance-id: storage-service

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
