server:
  port: 9999

spring:
  application:
    name: storage-service

eureka:
  instance:
    instance-id: storage-service

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
