server:
  port: 9999

spring:
  application:
    name: storage-service

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: d:\\temp\\spring_uploaded_files

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411

eureka:
  instance:
    instance-id: storage-service

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
