server:
  port: 9999

spring:
  application:
    name: storage-service

  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /data

  rabbitmq:
    port: 5672

  kafka:
    consumer:
      group-id: storage-service-group

minio:
  endpoint: http://localhost:9000
  bucketImageName: file-storage

eureka:
  instance:
    instance-id: storage-service

  client:
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
