server:
  port: 8100

spring:
  application:
    name: chat-store-service

  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}

  data:
    mongodb:

  kafka:
    consumer:
      group-id: chat-store
      auto-offset-reset: latest
      enable-auto-commit: false
    template:
      default-topic: modu.modu-chat.chat

eureka:
  instance:
    instance-id: chat-store-service

  client:
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
