server:
  port: 8110

spring:
  config:
    activate:
      on-profile: prod

  application:
    name: schedule-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/modu-chat?serverTimezone=Asia/Seoul
    username: root
    password: root1234

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

logging:
  level:
    org.hibernate.SQL: debug

management:
  server:
    port: 8082
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    instance-id: schedule-service

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka