server:
  port: 8110

spring:
  config:
    activate:
      on-profile: local

  application:
    name: schedule-service

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

logging:
  level:
    org.hibernate.SQL: debug

management:
  server:
    port: 8082
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    instance-id: schedule-service

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka