package com.example.pushservice.fcm.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.*;

import com.example.pushservice.fcm.entity.FcmToken;
import com.example.pushservice.fcm.repository.FcmRepository;
import java.util.Optional;
import org.junit.jupiter.api.Test;

class FcmServiceTokenTest {

    @Test
    void saveFcmToken_updatesExistingRowInsteadOfInserting() {
        FcmRepository repository = mock(FcmRepository.class);
        FcmService service = new FcmService(repository);

        FcmToken existing = new FcmToken("u1", "oldToken");
        setId(existing, 10L);
        when(repository.findFirstByUserIdOrderByIdDesc("u1")).thenReturn(Optional.of(existing));
        when(repository.save(any(FcmToken.class))).thenAnswer(invocation -> invocation.getArgument(0));

        FcmToken incoming = new FcmToken("u1", "newToken");
        FcmToken saved = service.saveFcmToken(incoming);

        assertEquals("newToken", saved.getFcmToken());
        assertEquals(existing, saved);
        verify(repository).save(existing);
        verify(repository, never()).save(incoming);
        verify(repository).deleteByUserIdAndIdNot("u1", 10L);
    }

    @Test
    void saveFcmToken_insertsWhenNoneExists() {
        FcmRepository repository = mock(FcmRepository.class);
        FcmService service = new FcmService(repository);

        when(repository.findFirstByUserIdOrderByIdDesc("u2")).thenReturn(Optional.empty());
        FcmToken incoming = new FcmToken("u2", "brandNewToken");
        when(repository.save(incoming)).thenReturn(incoming);
        setId(incoming, 20L);

        FcmToken saved = service.saveFcmToken(incoming);

        assertEquals(incoming, saved);
        verify(repository).save(incoming);
        verify(repository).deleteByUserIdAndIdNot("u2", 20L);
    }

    @Test
    void searchFcmToken_returnsNullWhenMissing() {
        FcmRepository repository = mock(FcmRepository.class);
        FcmService service = new FcmService(repository);

        when(repository.findFirstByUserIdOrderByIdDesc("nobody")).thenReturn(Optional.empty());

        assertNull(service.searchFcmToken("nobody"));
    }

    /** FcmToken.id is generated by the persistence provider; tests set it via reflection. */
    private static void setId(FcmToken token, Long id) {
        try {
            var field = FcmToken.class.getDeclaredField("id");
            field.setAccessible(true);
            field.set(token, id);
        } catch (ReflectiveOperationException e) {
            throw new RuntimeException(e);
        }
    }
}
