server:
  port: 9090

spring:
  application:
    name: chat-service

  profiles:
    active: dev

  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
