server:
  port: 9090

spring:
  application:
    name: chat-service

  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/modu-chat
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411

logging:
  level:
    org.hibernate.SQL: debug

eureka:
  instance:
    instance-id: chat-service

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka