server:
  port: 9090

spring:
  application:
    name: chat-service

  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/modu-chat?serverTimezone=Asia/Seoul
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug

eureka:
  instance:
    instance-id: chat-service

  client:
    register-with-eureka: true
    fetch-registry: true
