server:
  port: 9090

spring:
  application:
    name: chat-service

  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/modu-chat?serverTimezone=Asia/Seoul
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: chat-save-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    org.hibernate.SQL: debug

eureka:
  instance:
    instance-id: chat-service

  client:
    register-with-eureka: true
    fetch-registry: true

