server:
  port: 9090

spring:
  application:
    name: chat-service

  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/modu-chat?serverTimezone=Asia/Seoul
    username: root
    password: root1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411

logging:
  level:
    org.hibernate.SQL: debug

eureka:
  instance:
    instance-id: chat-service

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

rabbitmq:
  queue:
    queue1:
      name: modu-chat.queue
      exchange: modu-chat.exchange
    queue2:
      name: modu-chat-ws.queue
      exchange: modu-chat-ws.exchange
    routing:
      key:
        queue1: modu-chat.key
        queue2: modu-chat-ws.key
